package com.nexage.admin.core.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import java.io.Serializable;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

@Embeddable
public class CampaignCreativePk implements Serializable {

  /** generated by eclipse */
  private static final long serialVersionUID = -4938193819796449433L;

  @ManyToOne @JsonBackReference
  // @JsonIgnore
  private Campaign campaign;

  @ManyToOne
  // @JsonIgnore
  private Creative creative;

  public CampaignCreativePk() {}

  public CampaignCreativePk(Campaign campaign, Creative creative) {
    this.campaign = campaign;
    this.creative = creative;
  }

  public Campaign getCampaign() {
    return campaign;
  }

  public void setCampaign(Campaign campaign) {
    this.campaign = campaign;
  }

  public Creative getCreative() {
    return creative;
  }

  public void setCreative(Creative creative) {
    this.creative = creative;
  }

  @Override
  public boolean equals(Object o) {
    if (!(o instanceof CampaignCreativePk)) {
      return false;
    }
    CampaignCreativePk rhs = (CampaignCreativePk) o;

    return new EqualsBuilder()
        .append(campaign, rhs.getCampaign())
        .append(creative, rhs.getCreative())
        .isEquals();
  }

  @Override
  public int hashCode() {
    return new HashCodeBuilder(25, 37).append(campaign).append(creative).hashCode();
  }
}
