package com.nexage.admin.core.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@Entity
@Table(name = "as_template")
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@ToString(onlyExplicitlyIncluded = true)
@NoArgsConstructor
public class Template implements Serializable {

  /** generated by eclipse */
  private static final long serialVersionUID = 9152736017875108153L;

  @AllArgsConstructor
  @Getter
  public enum TemplateType {
    BANNER(0),
    TEXT(1),
    BANNER_AND_TEXT(2),
    PIXEL(3),
    PIXEL_EXT(4),
    CUSTOM_MARKUP(5);

    private final int externalValue;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(nullable = false)
  @EqualsAndHashCode.Include
  @ToString.Include
  private Long pid;

  @Column(nullable = false)
  @Enumerated(EnumType.ORDINAL)
  @EqualsAndHashCode.Include
  @ToString.Include
  private TemplateType type;

  @Column(nullable = false)
  @EqualsAndHashCode.Include
  @ToString.Include
  private int version;

  @Column(name = "markup_template", nullable = false)
  @EqualsAndHashCode.Include
  @ToString.Include
  private String markupTemplate;
}
