package com.nexage.app.dto.publisher;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.nexage.admin.core.enums.TierType;
import java.util.ArrayList;
import java.util.List;

@JsonInclude(Include.NON_NULL)
public class PublisherTierDTO {

  public enum OrderStrategy {
    Dynamic,
    Static;
  }

  private Long pid;
  private Integer version;
  private String name;
  private Integer level;
  private OrderStrategy orderStrategy;

  @JsonProperty("autogenerated")
  private Boolean isAutogenerated;

  private PublisherPositionDTO position;
  private List<PublisherTagWeightDTO> weights;
  private List<PublisherTagDTO> tags;
  private TierType tierType = TierType.WATERFALL;

  public PublisherTierDTO() {}

  private PublisherTierDTO(Builder builder) {
    this.pid = builder.pid;
    this.version = builder.version;
    this.name = builder.name;
    this.level = builder.level;
    this.position = builder.position;
    this.weights = builder.weights;
    this.tags = builder.tags;
    this.orderStrategy = builder.orderStrategy;
    this.isAutogenerated = builder.isAutogenerated;
    this.tierType = builder.tierType;
  }

  public Long getPid() {
    return pid;
  }

  public Integer getVersion() {
    return version;
  }

  public String getName() {
    return name;
  }

  public Integer getLevel() {
    return level;
  }

  public OrderStrategy getOrderStrategy() {
    return orderStrategy;
  }

  public PublisherPositionDTO getPosition() {
    return position;
  }

  public List<PublisherTagWeightDTO> getWeights() {
    return weights;
  }

  public List<PublisherTagDTO> getTags() {
    return tags;
  }

  public Boolean isAutogenerated() {
    return this.isAutogenerated;
  }

  public void removeTags() {
    this.tags.clear();
  }

  public void addTag(PublisherTagDTO tag) {
    if (this.tags == null) {
      tags = new ArrayList<PublisherTagDTO>();
    }
    this.tags.add(tag);
  }

  public TierType getTierType() {
    return tierType;
  }

  public static Builder newBuilder() {
    return new Builder();
  }

  public static final class Builder {
    private Long pid;
    private Integer version;
    private String name;
    private Integer level;
    private OrderStrategy orderStrategy;
    private PublisherPositionDTO position;
    private List<PublisherTagWeightDTO> weights;
    private List<PublisherTagDTO> tags;
    private Boolean isAutogenerated = false;
    private TierType tierType;

    public Builder withPid(Long pid) {
      this.pid = pid;
      return this;
    }

    public Builder withVersion(Integer version) {
      this.version = version;
      return this;
    }

    public Builder withName(String name) {
      this.name = name;
      return this;
    }

    public Builder withOrderStrategy(OrderStrategy orderStrategy) {
      this.orderStrategy = orderStrategy;
      return this;
    }

    public Builder withLevel(Integer level) {
      this.level = level;
      return this;
    }

    public Builder withPosition(PublisherPositionDTO position) {
      this.position = position;
      return this;
    }

    public Builder withTagWeight(PublisherTagWeightDTO tagWeight) {
      if (weights == null) {
        weights = new ArrayList<>();
      }
      this.weights.add(tagWeight);
      return this;
    }

    public Builder withTag(PublisherTagDTO tag) {
      if (tags == null) {
        tags = new ArrayList<>();
      }
      this.tags.add(tag);
      return this;
    }

    public Builder withIsAutogenerated(Boolean isAuto) {
      this.isAutogenerated = isAuto;
      return this;
    }

    public Builder withTierType(TierType tierType) {
      this.tierType = tierType;
      return this;
    }

    public PublisherTierDTO build() {
      return new PublisherTierDTO(this);
    }
  }

  public void setPid(Long pid) {
    this.pid = pid;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setLevel(Integer level) {
    this.level = level;
  }

  public void setOrderStrategy(OrderStrategy orderStrategy) {
    this.orderStrategy = orderStrategy;
  }

  public Boolean getAutogenerated() {
    return isAutogenerated;
  }

  public void setAutogenerated(Boolean autogenerated) {
    isAutogenerated = autogenerated;
  }

  public void setPosition(PublisherPositionDTO position) {
    this.position = position;
  }

  public void setWeights(List<PublisherTagWeightDTO> weights) {
    this.weights = weights;
  }

  public void setTags(List<PublisherTagDTO> tags) {
    this.tags = tags;
  }

  public void setTierType(TierType tierType) {
    this.tierType = tierType;
  }
}
