newrelic_agent_version: 8.12.0
newrelic_agent_lib_path: /etc/newrelic
newrelic_agent_lib_file_name: newrelic.jar
newrelic_license_key: '6ca51ca8124e1a287ceb70f3e0f9bdd2FFFFNRAL'
newrelic_agent_enabled: true
newrelic_app_name: geneva-api
newrelic_high_security: false
newrelic_enable_auto_app_naming: false
newrelic_enable_auto_transaction_naming: true
newrelic_log_level: info
newrelic_audit_mode: false
newrelic_log_file_count: 1
newrelic_log_limit_in_kbytes: 0
newrelic_log_daily: false
newrelic_log_file_name: newrelic_agent.log
newrelic_max_stack_trace_lines: 30
newrelic_attributes_enabled: true
newrelic_transaction_tracer: true
newrelic_transaction_tracer_log_sql: false
newrelic_error_collector_enabled: true
newrelic_transaction_events: true
newrelic_transaction_events_max_samples_stored: 2000
newrelic_distributed_tracing_enabled: false
newrelic_cross_application_tracer_enabled: true
newrelic_thread_profiler_enabled: true
newrelic_browser_monitoring_auto_instrument: true
newrelic_distributed_tracing_exclude_newrelic_header: false
newrelic_span_events_enabled: true
newrelic_span_events_attributes_enabled: true
newrelic_jfr_enabled: false
newrelic_jfr_audit_logging: false
