- name: "Configure Keystore"
  template:
    dest: "{{ geneva_server_home }}/bin/{{ item }}"
    group: root
    mode: 0755
    owner: root
    src: "{{ item }}.j2"
  with_items:
    - "configure-keystore"
