package com.nexage.geneva.model.crud;

public class Tag {

  private String pid;
  private String name;
  private String site_pid;
  private String status;
  private String primary_id;
  private String primary_name;
  private String secondary_id;
  private String secondary_name;
  private String ecpm_provision;
  private String ecpm_auto;
  private String owner;
  private String buyer_class;
  private String url_template;
  private String get_template;
  private String post_template;
  private String additional_get;
  private String additional_post;
  private String noad_regex;
  private String clickthrough_disable;
  private String ecpm_manual;
  private String adspaceid_template;
  private String adspacename_template;
  private String postprocess_template;
  private String httpheader_template;
  private String adnetreport_username;
  private String adnetreport_password;
  private String buyer_pid;
  private String id;
  private String version;
  private String monetization;
  private String return_raw_response;
  private String is_interstitial;
  private String ad_size;
  private String is_video_allowed;
  private String import_revenue_flag;
  private String position_pid;
  private String updated_on;
  private String height;
  private String width;
  private String video_linearity;
  private String video_support;
  private String screen_location;
  private String adnetreport_apikey;
  private String adnetreport_apitoken;
  private String autogenerated;

  public String getPid() {
    return pid;
  }

  public void setPid(String pid) {
    this.pid = pid;
  }

  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public String getSite_pid() {
    return site_pid;
  }

  public void setSite_pid(String site_pid) {
    this.site_pid = site_pid;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getIs_interstitial() {
    return is_interstitial;
  }

  public void setIs_interstitial(String is_interstitial) {
    if (is_interstitial != null) {
      if (is_interstitial.equals("0") || is_interstitial.equals("NO")) {
        this.is_interstitial = "false";
      } else if (is_interstitial.equals("1") || is_interstitial.equals("YES")) {
        this.is_interstitial = "true";
      } else {
        this.is_interstitial = is_interstitial;
      }
    } else {
      this.is_interstitial = null;
    }
  }

  public String getVideo_support() {
    return video_support;
  }

  public void setVideo_support(String video_support) {
    if (video_support != null) {
      switch (video_support) {
        case "BANNER":
          this.video_support = "0";
          break;
        case "VIDEO":
          this.video_support = "1";
          break;
        case "VIDEO_AND_BANNER":
          this.video_support = "2";
          break;
        case "NATIVE":
          this.video_support = "3";
          break;
        default:
          this.video_support = video_support;
          break;
      }
    } else {
      this.video_support = null;
    }
  }

  public String getScreenLocation() {
    return screen_location;
  }

  public void setScreenLocation(String screenLocation) {
    this.screen_location = screenLocation;
  }

  public String getAd_size() {
    return ad_size;
  }

  public void setAd_size(String ad_size) {
    this.ad_size = ad_size;
  }

  public String getHeight() {
    return height;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getPrimary_id() {
    return primary_id;
  }

  public void setPrimary_id(String primary_id) {
    this.primary_id = primary_id;
  }

  public String getPrimary_name() {
    return primary_name;
  }

  public void setPrimary_name(String primary_name) {
    this.primary_name = primary_name;
  }

  public String getSecondary_id() {
    return secondary_id;
  }

  public void setSecondary_id(String secondary_id) {
    this.secondary_id = secondary_id;
  }

  public String getSecondary_name() {
    return secondary_name;
  }

  public void setSecondary_name(String secondary_name) {
    this.secondary_name = secondary_name;
  }

  public String getEcpm_provision() {
    return ecpm_provision;
  }

  public void setEcpm_provision(String ecpm_provision) {
    this.ecpm_provision = ecpm_provision;
  }

  public String getEcpm_auto() {
    return ecpm_auto;
  }

  public void setEcpm_auto(String ecpm_auto) {
    this.ecpm_auto = ecpm_auto;
  }

  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public String getBuyer_class() {
    return buyer_class;
  }

  public void setBuyer_class(String buyer_class) {
    this.buyer_class = buyer_class;
  }

  public String getUrl_template() {
    return url_template;
  }

  public void setUrl_template(String url_template) {
    this.url_template = url_template;
  }

  public String getGet_template() {
    return get_template;
  }

  public void setGet_template(String get_template) {
    this.get_template = get_template;
  }

  public String getPost_template() {
    return post_template;
  }

  public void setPost_template(String post_template) {
    this.post_template = post_template;
  }

  public String getAdditional_get() {
    return additional_get;
  }

  public void setAdditional_get(String additional_get) {
    this.additional_get = additional_get;
  }

  public String getAdditional_post() {
    return additional_post;
  }

  public void setAdditional_post(String additional_post) {
    this.additional_post = additional_post;
  }

  public String getNoad_regex() {
    return noad_regex;
  }

  public void setNoad_regex(String noad_regex) {
    this.noad_regex = noad_regex;
  }

  public String getClickthrough_disable() {
    return clickthrough_disable;
  }

  public void setClickthrough_disable(String clickthrough_disable) {
    this.clickthrough_disable = clickthrough_disable;
  }

  public String getEcpm_manual() {
    return ecpm_manual;
  }

  public void setEcpm_manual(String ecpm_manual) {
    this.ecpm_manual = ecpm_manual;
  }

  public String getAdspaceid_template() {
    return adspaceid_template;
  }

  public void setAdspaceid_template(String adspaceid_template) {
    this.adspaceid_template = adspaceid_template;
  }

  public String getAdspacename_template() {
    return adspacename_template;
  }

  public void setAdspacename_template(String adspacename_template) {
    this.adspacename_template = adspacename_template;
  }

  public String getPostprocess_template() {
    return postprocess_template;
  }

  public void setPostprocess_template(String postprocess_template) {
    this.postprocess_template = postprocess_template;
  }

  public String getHttpheader_template() {
    return httpheader_template;
  }

  public void setHttpheader_template(String httpheader_template) {
    this.httpheader_template = httpheader_template;
  }

  public String getAdnetreport_username() {
    return adnetreport_username;
  }

  public void setAdnetreport_username(String adnetreport_username) {
    this.adnetreport_username = adnetreport_username;
  }

  public String getAdnetreport_password() {
    return adnetreport_password;
  }

  public void setAdnetreport_password(String adnetreport_password) {
    this.adnetreport_password = adnetreport_password;
  }

  public String getBuyer_pid() {
    return buyer_pid;
  }

  public void setBuyer_pid(String buyer_pid) {
    this.buyer_pid = buyer_pid;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getMonetization() {
    return monetization;
  }

  public void setMonetization(String mentization) {
    this.monetization = mentization;
  }

  public String getReturn_raw_response() {
    return return_raw_response;
  }

  public void setReturn_raw_response(String return_raw_response) {
    this.return_raw_response = return_raw_response;
  }

  public String getIs_video_allowed() {
    return is_video_allowed;
  }

  public void setIs_video_allowed(String is_video_allowed) {
    this.is_video_allowed = is_video_allowed;
  }

  public String getImport_revenue_flag() {
    return import_revenue_flag;
  }

  public void setImport_revenue_flag(String import_revenue_flag) {
    this.import_revenue_flag = import_revenue_flag;
  }

  public String getPosition_pid() {
    return position_pid;
  }

  public void setPosition_pid(String position_pid) {
    this.position_pid = position_pid;
  }

  public String getUpdated_on() {
    return updated_on;
  }

  public void setUpdated_on(String updated_on) {
    this.updated_on = updated_on;
  }

  public String getVideo_linearity() {
    return video_linearity;
  }

  public void setVideo_linearity(String video_linearity) {
    this.video_linearity = video_linearity;
  }

  public String getScreen_location() {
    return screen_location;
  }

  public void setScreen_location(String screen_location) {
    this.screen_location = screen_location;
  }

  public String getAdnetreport_apikey() {
    return adnetreport_apikey;
  }

  public void setAdnetreport_apikey(String adnetreport_apikey) {
    this.adnetreport_apikey = adnetreport_apikey;
  }

  public String getAdnetreport_apitoken() {
    return adnetreport_apitoken;
  }

  public void setAdnetreport_apitoken(String adnetreport_apitoken) {
    this.adnetreport_apitoken = adnetreport_apitoken;
  }

  public String getAutogenerated() {
    return autogenerated;
  }

  public void setAutogenerated(String autogenerated) {
    this.autogenerated = autogenerated;
  }

  public void setHeight(String height) {
    this.height = height;
  }

  public String getWidth() {
    return width;
  }

  public void setWidth(String width) {
    this.width = width;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(compareClones(o))) return false;
    Tag that = (Tag) o;

    if (pid != null ? !pid.equals(that.pid) : that.pid != null) return false;
    if (name != null ? !name.equals(that.name) : that.name != null) return false;
    if (site_pid != null ? !site_pid.equals(that.site_pid) : that.site_pid != null) return false;
    if (primary_id != null ? !primary_id.equals(that.primary_id) : that.primary_id != null)
      return false;
    if (primary_name != null ? !primary_name.equals(that.primary_name) : that.primary_name != null)
      return false;
    // if (secondary_id != null ? !secondary_id.equals(that.secondary_id) : that.secondary_id !=
    // null)
    //    return false;
    // if (secondary_name != null ? !secondary_name.equals(that.secondary_name) :
    // that.secondary_name != null)
    //    return false;
    if (id != null ? !id.equals(that.id) : that.id != null) return false;
    if (version != null ? !version.equals(that.version) : that.version != null) return false;
    if (position_pid != null ? !position_pid.equals(that.position_pid) : that.position_pid != null)
      return false;
    if (updated_on != null ? !updated_on.equals(that.updated_on) : that.updated_on != null)
      return false;
    return !(position_pid != null
        ? !position_pid.equals(that.position_pid)
        : that.position_pid != null);
  }

  @Override
  public int hashCode() {
    int result = pid != null ? pid.hashCode() : 0;
    result = 31 * result + (name != null ? name.hashCode() : 0);
    result = 31 * result + (site_pid != null ? site_pid.hashCode() : 0);
    result = 31 * result + (status != null ? status.hashCode() : 0);
    result = 31 * result + (primary_id != null ? primary_id.hashCode() : 0);
    result = 31 * result + (primary_name != null ? primary_name.hashCode() : 0);
    result = 31 * result + (secondary_id != null ? secondary_id.hashCode() : 0);
    result = 31 * result + (secondary_name != null ? secondary_name.hashCode() : 0);

    result = 31 * result + (ecpm_provision != null ? ecpm_provision.hashCode() : 0);
    result = 31 * result + (ecpm_auto != null ? ecpm_auto.hashCode() : 0);
    result = 31 * result + (owner != null ? owner.hashCode() : 0);
    result = 31 * result + (buyer_class != null ? buyer_class.hashCode() : 0);
    result = 31 * result + (url_template != null ? url_template.hashCode() : 0);
    result = 31 * result + (get_template != null ? get_template.hashCode() : 0);
    result = 31 * result + (post_template != null ? post_template.hashCode() : 0);
    result = 31 * result + (additional_get != null ? additional_get.hashCode() : 0);
    result = 31 * result + (additional_post != null ? additional_post.hashCode() : 0);
    result = 31 * result + (noad_regex != null ? noad_regex.hashCode() : 0);
    result = 31 * result + (clickthrough_disable != null ? clickthrough_disable.hashCode() : 0);
    result = 31 * result + (ecpm_manual != null ? ecpm_manual.hashCode() : 0);
    result = 31 * result + (adspaceid_template != null ? adspaceid_template.hashCode() : 0);
    result = 31 * result + (adspacename_template != null ? adspacename_template.hashCode() : 0);
    result = 31 * result + (postprocess_template != null ? postprocess_template.hashCode() : 0);
    result = 31 * result + (httpheader_template != null ? httpheader_template.hashCode() : 0);
    result = 31 * result + (adnetreport_username != null ? adnetreport_username.hashCode() : 0);
    result = 31 * result + (adnetreport_password != null ? adnetreport_password.hashCode() : 0);
    result = 31 * result + (id != null ? id.hashCode() : 0);
    result = 31 * result + (version != null ? version.hashCode() : 0);
    result = 31 * result + (monetization != null ? monetization.hashCode() : 0);
    result = 31 * result + (return_raw_response != null ? return_raw_response.hashCode() : 0);
    result = 31 * result + (is_interstitial != null ? is_interstitial.hashCode() : 0);
    result = 31 * result + (ad_size != null ? ad_size.hashCode() : 0);
    result = 31 * result + (is_video_allowed != null ? is_video_allowed.hashCode() : 0);
    result = 31 * result + (import_revenue_flag != null ? import_revenue_flag.hashCode() : 0);
    result = 31 * result + (position_pid != null ? position_pid.hashCode() : 0);
    result = 31 * result + (updated_on != null ? updated_on.hashCode() : 0);
    result = 31 * result + (height != null ? height.hashCode() : 0);
    result = 31 * result + (width != null ? width.hashCode() : 0);
    result = 31 * result + (video_linearity != null ? video_linearity.hashCode() : 0);
    result = 31 * result + (video_support != null ? video_support.hashCode() : 0);
    result = 31 * result + (screen_location != null ? screen_location.hashCode() : 0);
    result = 31 * result + (adnetreport_apikey != null ? adnetreport_apikey.hashCode() : 0);
    result = 31 * result + (adnetreport_apitoken != null ? adnetreport_apitoken.hashCode() : 0);
    result = 31 * result + (autogenerated != null ? autogenerated.hashCode() : 0);
    return result;
  }

  // Compares objects created through the clone api
  public boolean compareClones(Object o) {

    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    Tag that = (Tag) o;

    if (status != null ? !status.equals(that.status) : that.status != null) return false;
    if (secondary_id != null ? !secondary_id.equals(that.secondary_id) : that.secondary_id != null)
      return false;
    if (secondary_name != null
        ? !secondary_name.equals(that.secondary_name)
        : that.secondary_name != null) return false;
    if (ecpm_provision != null
        ? !ecpm_provision.equals(that.ecpm_provision)
        : that.ecpm_provision != null) return false;
    if (ecpm_auto != null ? !ecpm_auto.equals(that.ecpm_auto) : that.ecpm_auto != null)
      return false;
    if (owner != null ? !owner.equals(that.owner) : that.owner != null) return false;
    if (buyer_class != null ? !buyer_class.equals(that.buyer_class) : that.buyer_class != null)
      return false;
    if (url_template != null ? !url_template.equals(that.url_template) : that.url_template != null)
      return false;
    if (get_template != null ? !get_template.equals(that.get_template) : that.get_template != null)
      return false;
    if (post_template != null
        ? !post_template.equals(that.post_template)
        : that.post_template != null) return false;
    if (additional_get != null
        ? !additional_get.equals(that.additional_get)
        : that.additional_get != null) return false;
    if (additional_post != null
        ? !additional_post.equals(that.additional_post)
        : that.additional_post != null) return false;
    if (noad_regex != null ? !noad_regex.equals(that.noad_regex) : that.noad_regex != null)
      return false;
    if (clickthrough_disable != null
        ? !clickthrough_disable.equals(that.clickthrough_disable)
        : that.clickthrough_disable != null) return false;
    if (ecpm_manual != null ? !ecpm_manual.equals(that.ecpm_manual) : that.ecpm_manual != null)
      return false;
    if (adspaceid_template != null
        ? !adspaceid_template.equals(that.adspaceid_template)
        : that.adspaceid_template != null) return false;
    if (adspacename_template != null
        ? !adspacename_template.equals(that.adspacename_template)
        : that.adspacename_template != null) return false;
    if (postprocess_template != null
        ? !postprocess_template.equals(that.postprocess_template)
        : that.postprocess_template != null) return false;
    if (httpheader_template != null
        ? !httpheader_template.equals(that.httpheader_template)
        : that.httpheader_template != null) return false;
    if (adnetreport_username != null
        ? !adnetreport_username.equals(that.adnetreport_username)
        : that.adnetreport_username != null) return false;
    if (adnetreport_password != null
        ? !adnetreport_password.equals(that.adnetreport_password)
        : that.adnetreport_password != null) return false;
    if (buyer_pid != null ? !buyer_pid.equals(that.buyer_pid) : that.buyer_pid != null)
      return false;
    if (monetization != null ? !monetization.equals(that.monetization) : that.monetization != null)
      return false;
    if (return_raw_response != null
        ? !return_raw_response.equals(that.return_raw_response)
        : that.return_raw_response != null) return false;
    if (is_interstitial != null
        ? !is_interstitial.equals(that.is_interstitial)
        : that.is_interstitial != null) return false;
    if (ad_size != null ? !ad_size.equals(that.ad_size) : that.ad_size != null) return false;

    if (is_video_allowed != null
        ? !is_video_allowed.equals(that.is_video_allowed)
        : that.is_video_allowed != null) return false;
    if (import_revenue_flag != null
        ? !import_revenue_flag.equals(that.import_revenue_flag)
        : that.import_revenue_flag != null) return false;
    if (height != null ? !height.equals(that.height) : that.height != null) return false;
    if (width != null ? !width.equals(that.width) : that.width != null) return false;

    if (video_linearity != null
        ? !video_linearity.equals(that.video_linearity)
        : that.video_linearity != null) return false;
    if (video_support != null
        ? !video_support.equals(that.video_support)
        : that.video_support != null) return false;
    if (screen_location != null
        ? !screen_location.equals(that.screen_location)
        : that.screen_location != null) return false;
    if (adnetreport_apikey != null
        ? !adnetreport_apikey.equals(that.adnetreport_apikey)
        : that.adnetreport_apikey != null) return false;
    if (adnetreport_apitoken != null
        ? !adnetreport_apitoken.equals(that.adnetreport_apitoken)
        : that.adnetreport_apitoken != null) return false;
    return true;
  }

  // Compares objects created through the clone api for mediation tags
  public boolean compareClonesMediationTags(Object o) {

    if (this == o) return true;
    if (!(compareClones(o))) return false;
    Tag that = (Tag) o;
    if (primary_id != null ? !primary_id.equals(that.primary_id) : that.primary_id != null)
      return false;
    if (primary_name != null ? !primary_name.equals(that.primary_name) : that.primary_name != null)
      if (secondary_id != null
          ? !secondary_id.equals(that.secondary_id)
          : that.secondary_id != null) return false;
    if (secondary_name != null
        ? !secondary_name.equals(that.secondary_name)
        : that.secondary_name != null) return false;
    return true;
  }
}
