package com.nexage.geneva.model.crud;

public class Tier {

  public String pid;
  public String level;
  public String position_id;
  public String order_statergy;
  public String version;
  public String autogenerated;

  public String getPid() {
    return pid;
  }

  public void setPid(String pid) {
    this.pid = pid;
  }

  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public String getPosition_id() {
    return position_id;
  }

  public void setPosition_id(String position_id) {
    this.position_id = position_id;
  }

  public String getOrder_statergy() {
    return order_statergy;
  }

  public void setOrder_statergy(String order_statergy) {
    this.order_statergy = order_statergy;
  }

  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public String getAutogenerated() {
    return autogenerated;
  }

  public void setAutogenerated(String autogenerated) {
    this.autogenerated = autogenerated;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(compareClones(o))) return false;
    Tier that = (Tier) o;

    if (pid != null ? !pid.equals(that.pid) : that.pid != null) return false;
    if (position_id != null ? !position_id.equals(that.position_id) : that.position_id != null)
      return false;
    return !(version != null ? !version.equals(that.version) : that.version != null);
  }

  public boolean compareClones(Object o) {

    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Tier that = (Tier) o;

    if (level != null ? !level.equals(that.level) : that.level != null) return false;
    if (order_statergy != null
        ? !order_statergy.equals(that.order_statergy)
        : that.order_statergy != null) return false;
    return !(autogenerated != null
        ? !autogenerated.equals(that.autogenerated)
        : that.autogenerated != null);
  }
}
